spring:
  application:
    name: webflux
  data:
    mongodb:
      uri: mongodb+srv://${DB_USER:admin}:${DB_PASSWORD}@webfluxcluster.fcxf67l.mongodb.net/${DB_NAME:webfluxdb}?retryWrites=true&w=majority
      auto-index-creation: true